name: TP4-CD

on:
  push:
    branches:
      - main
      - develop/yves
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup java 21
        uses: actions/setup-java@v4
        with:
            distribution: 'adopt'
            java-version: '21'

      - name: Install dependencies
        run: ./mvnw install -DskipTests

      - name: Run unit tests
        run: ./mvnw test

  build:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup java 21
        uses: actions/setup-java@v4
        with:
            distribution: 'adopt'
            java-version: '21'

      - name: Install dependencies
        run: ./mvnw install -DskipTests

      - name: Build
        run: ./mvnw clean package -DskipTests