name: TP4-CD

on:
  push:
    branches:
      - main
      - develop/yves
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup java 21
        uses: actions/setup-java@v4
        with:
            distribution: 'adopt'
            java-version: '21'

      - name: Install dependencies
        run: ./mvnw install -DskipTests

      - name: Run unit tests
        run: ./mvnw test

  build-on-docker:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker image build -t ${{ secrets.DOCKER_USERNAME }}/my_springboot_app:main -f Dockerfile .

#  build:
#    needs: build-on-docker
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Setup java 21
#        uses: actions/setup-java@v4
#        with:
#            distribution: 'adopt'
#            java-version: '21'
#
#      - name: Install dependencies
#        run: ./mvnw install -DskipTests
#
#      - name: Build
#        run: ./mvnw clean package -DskipTests

  push-to-docker:
    needs: build-on-docker
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4

#      - name: Build Docker image
#        run: docker image build -t ${{ secrets.DOCKER_USERNAME }}/my_springboot_app:main -f Dockerfile .

      - name: Push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_USERNAME/my_springboot_app:main